#!/usr/bin/env python3
"""Validate the standalone native API reference generated by Docusaurus.

The repository inventory determines symbol coverage, but source snapshots and
project provenance must never enter the public site. Checks every generated
symbol route, Markdown page, search entry, and internal HTML link/fragment.
"""
from __future__ import annotations

import argparse
from collections import Counter
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from native_inventory import load_inventory
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
BASE_PATH = "/mnsg-documentation/"
PROJECT_NAMES = ("mnsg-custom-fish", "mnsg-enable-boss-rush", "mnsg-extra-options", "mnsg-recomp-example", "mnsg-team-up", "mnsg-anchor")
# Boss Rush describes a native feature; the authorized phrase "mod development"
# describes the reference audience. Other mod/project references remain blocked.
FORBIDDEN_PROSE = re.compile(r"\b(?:" + "|".join(map(re.escape, PROJECT_NAMES)) + r"|extra[ _-]options|team[ _-]up|custom[ _-]fish|anchor|multiplayer|mod(?!\s+development\b)|mods)\b", re.I)
FORBIDDEN_IDENTIFIERS = re.compile(r"\b(?:[a-zA-Z0-9]+_)*(?:extra_options|team_up|anchor)_[A-Za-z0-9_]*\b", re.I)
FORBIDDEN_SECTIONS = re.compile(r"\b(?:examples from the mods|source evidence|all references|sources? [&and]+ coverage|scanned projects|project filter)\b", re.I)
VOID_TAGS = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}


class Page(HTMLParser):
    def __init__(self, content):
        super().__init__(convert_charrefs=True)
        self.ids, self.duplicate_ids, self.links = set(), [], []
        self.search_inputs = []
        self.main_text, self.article_text, self.headings = [], [], []
        self.table_rows, self._row, self._cell = [], None, None
        self.tables_by_heading, self._heading, self._table, self._header_row = {}, None, None, False
        self.code_blocks, self.stack = 0, []
        self.feed(content)
        self.close()

    def handle_starttag(self, tag, pairs):
        attrs = dict(pairs)
        if tag == 'tr':
            self._row = []
            self._header_row = False
        if tag in {'td', 'th'}:
            self._cell = []
            self._header_row = self._header_row or tag == 'th'
        identity = attrs.get("id")
        if tag in {'h2','h3'}:
            self._heading = identity
        if tag == 'table':
            self._table = {'headers': [], 'rows': []}
            self.tables_by_heading.setdefault(self._heading, []).append(self._table)
        if tag == "input" and attrs.get("name") == "q":
            self.search_inputs.append(attrs)
        if identity:
            if identity in self.ids:
                self.duplicate_ids.append(identity)
            self.ids.add(identity)
        for attribute in ("href", "src", "action"):
            if attrs.get(attribute):
                self.links.append({"url": attrs[attribute], "tag": tag, "attribute": attribute})
        if tag == "pre" and any(node["tag"] in {"main", "article"} for node in self.stack):
            self.code_blocks += 1
        if tag not in VOID_TAGS:
            self.stack.append({"tag": tag, "attrs": attrs})

    def handle_endtag(self, tag):
        if tag in {'td','th'} and self._cell is not None and self._row is not None:
            self._row.append(''.join(self._cell))
            self._cell = None
        if tag == 'tr' and self._row is not None:
            self.table_rows.append(tuple(self._row))
            if self._table is not None:
                self._table['headers' if self._header_row else 'rows'].append(tuple(self._row))
            self._row = None
        if tag == 'table':
            self._table = None
        for i in range(len(self.stack) - 1, -1, -1):
            if self.stack[i]["tag"] == tag:
                del self.stack[i:]
                break

    def handle_data(self, text):
        tags = {node["tag"] for node in self.stack}
        if "script" in tags or "style" in tags:
            return
        if self._cell is not None:
            self._cell.append(text)
        if "main" in tags:
            self.main_text.append(text)
        if "article" in tags:
            self.article_text.append(text)
        if tags & {"h1", "h2", "h3"}:
            self.headings.append(text)

    @property
    def body(self):
        return "".join(self.article_text or self.main_text)


def public_content_errors(content: str, label: str):
    errors = []
    for pattern, description in ((FORBIDDEN_PROSE, "project or mod reference"),
                                 (FORBIDDEN_IDENTIFIERS, "project-specific code identifier"),
                                 (FORBIDDEN_SECTIONS, "provenance or project section")):
        matches = sorted({match[0] for match in pattern.finditer(content)})
        if matches:
            errors.append(f"{label}: public page contains {description}: {', '.join(matches)}")
    if re.search(r"(?mi)^\s*#{1,6}\s+used by\s*$", content):
        errors.append(f"{label}: public page contains a Used by provenance heading.")
    if re.search(r"(?:/Users/|/home/|file://|localhost(?::\d+)?|127\.0\.0\.1)", content):
        errors.append(f"{label}: public content contains a local development path or address.")
    return errors


def validate_links(site: Path, pages: dict[Path, Page], base_path=BASE_PATH):
    site = site.resolve()
    pages = {path.resolve(): page for path, page in pages.items()}
    errors, checked = [], 0
    for path, page in pages.items():
        label = str(path.relative_to(site))
        for fragment in page.duplicate_ids:
            errors.append(f"{label}: duplicate fragment #{fragment}")
        for link in page.links:
            raw = link["url"]
            try:
                url = urlsplit(raw)
            except ValueError:
                errors.append(f"{label}: malformed URL {raw!r}")
                continue
            if url.hostname in {"localhost", "127.0.0.1", "0.0.0.0", "::1"}:
                errors.append(f"{label}: development-only link {raw}")
            decoded = unquote(url.path)
            if url.hostname in {"github.com", "www.github.com", "raw.githubusercontent.com"} and any(re.search(r"(?:^|/)" + re.escape(project) + r"(?:/|$)", decoded, re.I) for project in PROJECT_NAMES):
                errors.append(f"{label}: link to a mod repository is public: {raw}")
            same_site = url.hostname == "8ae.github.io" and decoded.startswith(base_path)
            if not same_site and (url.scheme in {"http", "https", "mailto", "tel"} or url.netloc):
                continue
            if url.scheme == "data" and link["attribute"] == "src":
                continue
            if url.scheme and not same_site:
                errors.append(f"{label}: unsupported or nonportable link {raw}")
                continue
            if decoded.startswith(base_path):
                target = (site / decoded[len(base_path):]).resolve()
            elif decoded.startswith("/"):
                errors.append(f"{label}: absolute link misses GitHub Pages base path: {raw}")
                continue
            else:
                target = (path.parent / decoded).resolve() if decoded else path
            if not target.is_relative_to(site):
                errors.append(f"{label}: link escapes published site: {raw}")
                continue
            relative_parts = target.relative_to(site).parts
            if relative_parts and relative_parts[0] in {"sources", "coverage", "projects", "data"}:
                errors.append(f"{label}: public link exposes internal provenance: {raw}")
            if target.is_dir():
                target /= "index.html"
            checked += 1
            if not target.is_file():
                errors.append(f"{label}: missing target {raw}")
                continue
            if url.fragment and target.suffix == ".html":
                destination = pages.get(target)
                if destination is None or unquote(url.fragment) not in destination.ids:
                    errors.append(f"{label}: missing fragment {raw}")
    return errors, checked


def markdown_body(content):
    return re.sub(r"\A---\s*\n.*?\n---\s*\n", "", content, count=1, flags=re.S)

def plain_table_cell(value):
    value = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', value)
    return ' '.join(value.replace('`','').replace('\\|','|').split())

def value_table_errors(name, record, page):
    errors = []
    for table in record.get('tables', []):
        label = f'{name}/{table["id"]}'
        if table['id'] not in page.ids:
            errors.append(f'{label}: rendered value table anchor is missing.')
        matches = page.tables_by_heading.get(table['id'], [])
        if len(matches) != 1:
            errors.append(f'{label}: expected exactly one table under its heading.')
            continue
        rendered = matches[0]
        normalize = lambda rows: [tuple(' '.join(cell.split()) for cell in row) for row in rows]
        expected_headers = [tuple(plain_table_cell(c) for c in table['columns'])]
        expected_rows = [tuple(plain_table_cell(c) for c in row) for row in table['rows']]
        if normalize(rendered['headers']) != expected_headers:
            errors.append(f'{label}: rendered value-table column headers differ.')
        if normalize(rendered['rows']) != expected_rows:
            errors.append(f'{label}: rendered value rows differ or are out of order.')
    return errors

def value_search_errors(name, record, entry):
    parts = []
    for table in record['tables']:
        parts.extend([table['title'], table['description'], *table['columns']])
        parts.extend(cell for row in table['rows'] for cell in row)
    expected = ' '.join(parts).replace('`', '')
    if entry.get('values') != expected:
        return [f'{name}: search index differs from reviewed value interpretations.']
    return []


def search_entries(site):
    candidates = [site / "api-index.json", site / "search-index.json", site / "symbols.json"]
    candidates.extend(site.glob("search-index-*.json"))
    for path in candidates:
        if path.is_file():
            value = json.loads(path.read_text())
            if isinstance(value, dict):
                value = value.get("symbols", value.get("entries", value.get("items", [])))
            if isinstance(value, list):
                return path, value
    return None, []


def validate_site(site: Path, data_dir: Path | None = None, docs_dir: Path | None = None, base_path=BASE_PATH):
    site = site.resolve()
    data_dir = (data_dir or ROOT / "data").resolve()
    docs_dir = (docs_dir or ROOT / "docs").resolve()
    if not site.is_dir():
        return {"ok": False, "errors": [f"Docusaurus output is absent: {site}. Run npm run build first."]}
    try:
        inventory = load_inventory(data_dir)
        pages = {path.resolve(): Page(path.read_text()) for path in site.rglob("*.html")}
    except (OSError, json.JSONDecodeError) as error:
        return {"ok": False, "errors": [f"Cannot read required site data: {error}"]}
    errors, checked = validate_links(site, pages, base_path)
    symbols = {symbol["name"]: symbol for symbol in inventory["symbols"]}
    if len(symbols) != len(inventory["symbols"]):
        errors.append("Inventory contains duplicate native symbol names.")
    names = set(symbols)
    value_records = {}
    for path in sorted(data_dir.glob('values-*.json')):
        value_records.update(json.loads(path.read_text()))
    expected_routes = {(Path("functions" if symbol["kind"] == "function" else "variables") / name / "index.html") for name, symbol in symbols.items()}
    actual_routes = {path.relative_to(site) for group in ("functions", "variables") for path in (site / group).glob("*/index.html")}
    if actual_routes != expected_routes:
        errors.append(f"Native route coverage differs: missing={sorted(map(str, expected_routes-actual_routes))}, stale={sorted(map(str, actual_routes-expected_routes))}")
    expected_docs = {Path("functions" if symbol["kind"] == "function" else "variables") / f"{name}.md" for name, symbol in symbols.items()}
    actual_docs = {path.relative_to(docs_dir) for group in ("functions", "variables") for path in (docs_dir / group).glob("*.md") if path.stem not in {"index", "_category_"}}
    if actual_docs != expected_docs:
        errors.append(f"Generated Markdown coverage differs: missing={sorted(map(str, expected_docs-actual_docs))}, stale={sorted(map(str, actual_docs-expected_docs))}")
    for name, symbol in symbols.items():
        group = "functions" if symbol["kind"] == "function" else "variables"
        document = docs_dir / group / f"{name}.md"
        if document.is_file():
            body = markdown_body(document.read_text())
            errors.extend(public_content_errors(body, str(document.relative_to(docs_dir))))
            for heading in ("How it works", "Usage example"):
                if not re.search(r"^##\s+" + re.escape(heading) + r"\s*$", body, re.M):
                    errors.append(f"{name}: missing standalone {heading} section.")
            if not re.search(r"^##\s+(?:Signature|Interface)\s*$", body, re.M):
                errors.append(f"{name}: missing native signature or interface explanation.")
            if name not in body:
                errors.append(f"{name}: public documentation does not identify the native symbol.")
            snippets = re.findall(r"```(?:c|cpp|h)\b[^\n]*\n(.*?)```", body, flags=re.S)
            if not snippets or not any(name in snippet for snippet in snippets):
                errors.append(f"{name}: missing a C declaration or usage example containing the native symbol.")
            prose = re.sub(r"```.*?```", "", body, flags=re.S)
            prose = re.sub(r"^\|.*$|^#{1,6}.*$", "", prose, flags=re.M).strip()
            if len(prose) < 100:
                errors.append(f"{name}: native behavior prose is missing or too sparse.")
        page = pages.get(site / group / name / "index.html")
        if page is not None:
            for fragment in ("how-it-works", "usage-example"):
                if fragment not in page.ids:
                    errors.append(f"{name}: rendered native page lacks #{fragment}.")
            if name not in page.body:
                errors.append(f"{name}: rendered native page omits its symbol identifier.")
            if not page.code_blocks:
                errors.append(f"{name}: rendered native page contains no C code block.")
            if len(page.body.strip()) < 150:
                errors.append(f"{name}: rendered native page lacks behavioral documentation.")
            errors.extend(value_table_errors(name, value_records.get(name, {}), page))
    # Inspect every authored public page, including guides and catalog landing pages.
    for document in docs_dir.rglob("*.md"):
        if document.relative_to(docs_dir) not in expected_docs:
            errors.extend(public_content_errors(markdown_body(document.read_text()), str(document.relative_to(docs_dir))))
    for path, page in pages.items():
        errors.extend(public_content_errors(page.body, str(path.relative_to(site))))
        if any(heading.strip().lower() == "used by" for heading in page.headings):
            errors.append(f"{path.relative_to(site)}: public page contains a Used by provenance heading.")
        if {"project-filter", "role-filter", "source-code", "symbol-rows"} & page.ids:
            errors.append(f"{path.relative_to(site)}: obsolete project/provenance UI remains public.")
    leaked = []
    for path in site.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(site)
        if relative.parts[0] in {"sources", "coverage", "projects", "data"} or path.name in {"inventory.json", "source-snapshots.json", "build-report.json", "coverage.html"} or re.match(r"(?:annotations|value-evidence)-.*\.json$", path.name):
            leaked.append(str(relative))
    if leaked:
        errors.append(f"Internal research/provenance files were published: {', '.join(sorted(leaked))}")
    try:
        search_path, entries = search_entries(site)
    except (OSError, json.JSONDecodeError) as error:
        search_path, entries = None, []
        errors.append(f"Cannot read native search index: {error}")
    if search_path is None:
        errors.append("Missing public native search index (api-index.json or search-index.json).")
    else:
        search_names = [entry.get("name") for entry in entries]
        if set(search_names) != names or len(search_names) != len(names):
            errors.append(f"Native search coverage differs: missing={sorted(names-set(search_names))}, unexpected={sorted(set(search_names)-names, key=str)}, duplicates={sorted(str(name) for name,count in Counter(search_names).items() if count > 1)}")
        errors.extend(public_content_errors(json.dumps(entries, ensure_ascii=False), search_path.name))
        for entry in entries:
            name = entry.get("name")
            symbol = symbols.get(name)
            if any(key in entry for key in ("projects", "references", "symbolSources", "sourceFiles", "evidence")):
                errors.append(f"{name}: search index includes internal provenance fields.")
            if symbol and entry.get("kind") != symbol["kind"]:
                errors.append(f"{name}: search kind differs from native inventory.")
            if not entry.get("title") or not entry.get("summary"):
                errors.append(f"{name}: search entry lacks a native description.")
            if name in value_records:
                errors.extend(value_search_errors(name, value_records[name], entry))
            route = entry.get("route", entry.get("url", entry.get("path")))
            if not route:
                errors.append(f"{name}: search entry lacks a native route.")
            if route and symbol:
                normalized = urlsplit(route).path
                if normalized.startswith(base_path):
                    normalized = normalized[len(base_path):]
                expected = f'{"functions" if symbol["kind"] == "function" else "variables"}/{name}/'
                if normalized.lstrip("/") != expected:
                    errors.append(f"{name}: search entry points to incorrect native route {route}.")
    return {"ok": not errors, "htmlPages": len(pages), "checkedInternalLinks": checked,
            "symbols": len(names), "functionPages": sum(s["kind"] == "function" for s in symbols.values()),
            "variablePages": sum(s["kind"] == "variable" for s in symbols.values()),
            "variablesWithValues": len(value_records),
            "valueTables": sum(len(record['tables']) for record in value_records.values()),
            "valueRows": sum(len(table['rows']) for record in value_records.values() for table in record['tables']),
            "searchEntries": len(entries), "publicSourceFiles": len(leaked), "errors": errors}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, default=ROOT / "build")
    parser.add_argument("--data", type=Path, default=ROOT / "data")
    parser.add_argument("--docs", type=Path, default=ROOT / "docs")
    parser.add_argument("--base-path", default=BASE_PATH)
    args = parser.parse_args()
    report = validate_site(args.site, args.data, args.docs, args.base_path)
    print(json.dumps(report, indent=2))
    raise SystemExit(0 if report["ok"] else 1)


if __name__ == "__main__":
    main()
